---
# tasks file for generate_agent_files
- name: Create install-config.yaml
  ansible.builtin.copy:
    dest: "{{ work_dir }}/install-config.yaml"
    mode: '0755'
    src: install-config.yaml

- name: Create agent-config.yaml
  ansible.builtin.copy:
    dest: "{{ work_dir }}/agent-config.yaml"
    mode: '0755'
    src: agent-config.yaml