allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    operator.libopenstorage.org/managed-by: portworx
  name: pure-fb-nfsv4
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
mountOptions:
- nfsvers=4.1
- tcp
parameters:
  backend: pure_file
  pure_nfs_policy: 'infra-policy'
  pure_nfs_server: "infra-server"
  pure_nfs_export_rules_client: "10.8.0.0/24"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
