{{- if not .Values.ignoreHelmHooks }}
---
apiVersion: v1
kind: Pod
metadata:
  name: crd-and-mch-check 
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Values.acm.namespace }}
spec:
  containers:
  - name: crd-and-mch-check 
    securityContext:
      allowPrivilegeEscalation: false
    image: {{ .Values.image }}
    imagePullPolicy: IfNotPresent
    command: 
      - sh
      - -c
      - | 
        while true; do
          oc get crd multiclusterhubs.operator.open-cluster-management.io >/dev/null 2>&1  && break
          sleep 5
        done
        echo "CRD present, waiting for MCH validating webhook to be reachable ..."
        while true; do
          EP=$(oc get endpoints multiclusterhub-operator-webhook -n {{ .Values.acm.namespace }} -o jsonpath='{.subsets[*].addresses[*].ip}' 2>/dev/null)
          [ -n "$EP" ] && break
          sleep 5
        done
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  serviceAccount: default
  serviceAccountName: default
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
{{- end }}
