apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: {{ cluster_name }}
hosts:
  - hostname: {{ master1_hostname }}
    role: master
    interfaces:
      - name: eno1
        macAddress: "{{ master1_mac }}"
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          ipv4:
            enabled: true
            address:
              - ip: {{ rendezvous_ip }}
                prefixLength: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - "{{ dns_ip }}"
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gateway_ip }}
            next-hop-interface: eno1