all:
  children:
    infra:
      hosts:
        infra-cluster:
          ansible_connection: local
    infra-dev:
      hosts:
        infra-dev-cluster:
          ansible_connection: local
    staging:
      hosts:
        staging-cluster:
          ansible_connection: local
